-- precinct data seed names
INSERT INTO precinct_names(precinct, name) VALUES
(0, 'RICE MEMORIAL CENTER - RICE UNIVERSITY ENTRANCE 20'),
(1, 'GIRL SCOUTS OF SAN JACINTO COUNCIL - 3000 SOUTHWEST FREEWAY'),
(2, 'ACRES HOMES MULTI SERVICE CENTER - 6719 WEST MONTGOMERY ROAD'),
(3, 'ADAM ELEMENTARY SCHOOL - 11303 HONEY GROVE LANE'),
(4, 'ALBRIGHT MIDDLE SCHOOL - 6315 WINKLEMAN ROAD'),
(5, 'ALDINE MIDDLE SCHOOL - 14908 ALDINE WESTFIELD ROAD'),
(6, 'ALEXANDER ELEMENTARY SCHOOL - 8500 BROOKWULF DRIVE'),
(7, 'ALICE JOHNSON JUNIOR HIGH SCHOOL - 15500 PROCTOR STREET'),
(8, 'BAKERRIPLEY EAST ALDINE CAMPUS - 3000 ALDINE MAIL ROUTE ROAD'),
(9, 'CYPRESS FAIRBANKS EXHIBIT CENTER - 11206 TELGE ROAD'),
(10, 'HARRIS COUNTY COURTHOUSE ANNEX NUM 8 - 701 WEST BAKER ROAD');
